version: "2"
services:
  subscription:
    extends:
      file: docker-compose.yml
      service: subscription
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
    ports:
      - 3306:3306
